name: "Build & Publish Docker Image (CD)"

on:
  push:
    branches:
      - main
      - dev
      - nix
  workflow_dispatch:

env:
  IMAGE_NAME: ubermetroid/todo
  PLATFORMS: linux/amd64

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: write
      id-token: write
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image with Nix
        run: nix build .#dockerImage

      - name: Log in to Docker Hub
        if: ${{ env.DOCKER_USERNAME != '' && env.DOCKER_PASSWORD != '' }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Extract version from backend/Cargo.toml
        id: package_version
        run: |
          VERSION=$(grep -m 1 '^version = ' backend/Cargo.toml | cut -d '"' -f 2)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Generate Docker Tags
        id: meta
        run: |
          VERSION=${{ steps.package_version.outputs.VERSION }}
          LOWER_IMAGE_NAME=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')

          DOCKER_TAGS="${LOWER_IMAGE_NAME}:${VERSION}"
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            DOCKER_TAGS="${DOCKER_TAGS},${LOWER_IMAGE_NAME}:latest"
          elif [ "${{ github.ref }}" = "refs/heads/dev" ]; then
            DOCKER_TAGS="${DOCKER_TAGS},${LOWER_IMAGE_NAME}:dev"
          elif [ "${{ github.ref }}" = "refs/heads/nix" ]; then
            DOCKER_TAGS="${DOCKER_TAGS},${LOWER_IMAGE_NAME}:nix"
          fi

          echo "DOCKER_TAGS=${DOCKER_TAGS}" >> $GITHUB_OUTPUT
          echo "Generated tags: ${DOCKER_TAGS}"

      - name: Load image into Docker
        run: |
          docker load < result

      - name: Push to Docker Hub
        if: ${{ env.DOCKER_USERNAME != '' && env.DOCKER_PASSWORD != '' }}
        run: |
          IFS=',' read -ra DH_TAGS <<< "${{ steps.meta.outputs.DOCKER_TAGS }}"
          for tag in "${DH_TAGS[@]}"; do
            docker tag todo-nix:latest "$tag"
            docker push "$tag"
          done
